services:
  nginx_single_server:
    image: nginx:stable-alpine
    ports:
    - 80:80
    - 443:443
    volumes:
    - ./data/nginx:/etc/nginx/conf.d
    - ./data/logs/:/var/log/nginx
    - ./data/certbot/conf:/etc/letsencrypt
    - ./data/certbot/www:/var/www/certbot
    - ./data/static_files:/app/static_files
    - ./data/well-known:/app/well-known
    command: /bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g "daemon off;"'
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "-q", "--spider", "http://localhost/healthcheck"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    depends_on:
    - certbot

  certbot:
    image: certbot/certbot
    volumes:
    - ./data/certbot/conf:/etc/letsencrypt
    - ./data/certbot/www:/var/www/certbot
    entrypoint: /bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'
    restart: unless-stopped

networks:
  default:
    name: trufi-server
